import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { renderToStaticMarkup } from "react-dom/server";
import { MemoryReferenceAntiphonProvider } from "../src/application/reference-antiphon";
import type { ReferenceAntiphonRecord } from "../src/application/reference-antiphon-contract";
import { ServiceContextReferenceAntiphonFieldView } from "../app/service-context-reference-antiphon-field";
import { ServiceContextReferenceAntiphonUiState } from "../src/application/service-context-reference-antiphon-ui-state";
import { serviceAntiphonMatchesLanguage } from "../src/planning-lifecycle";

const fixtures: ReferenceAntiphonRecord[] = [
  { id:"polish:2",language:"polish",canonicalNumber:2,displayNumber:"2",title:"Polska druga" },
  { id:"czech:801",language:"czech",canonicalNumber:801,displayNumber:"801",title:"Česká druhá",sourceUrl:"https://www.evangelickykancional.cz/czech-801" },
  { id:"polish:1",language:"polish",canonicalNumber:1,displayNumber:"1",title:"Polska pierwsza" },
  { id:"czech:800",language:"czech",canonicalNumber:800,displayNumber:"800",title:"Česká první",sourceUrl:"https://www.evangelickykancional.cz/czech-800" },
];
async function providerCoverage(){const provider=new MemoryReferenceAntiphonProvider(fixtures);assert.deepEqual((await provider.list({language:"all",pageSize:20})).records.map(r=>r.id),["czech:800","czech:801","polish:1","polish:2"]);assert.deepEqual((await provider.list({language:"polish"})).records.map(r=>r.id),["polish:1","polish:2"]);assert.deepEqual((await provider.list({search:"80"})).records.map(r=>r.id),["czech:800","czech:801"]);assert.deepEqual((await provider.list({search:"PIERWS"})).records.map(r=>r.id),["polish:1"]);}
function languageCoverage(){const c={id:"czech:800",displayNumber:"800",title:"C"};const p={id:"polish:1",displayNumber:"1",title:"P"};assert.equal(serviceAntiphonMatchesLanguage(c,"czech"),true);assert.equal(serviceAntiphonMatchesLanguage(c,"polish"),false);assert.equal(serviceAntiphonMatchesLanguage(c,"mixed"),true);assert.equal(serviceAntiphonMatchesLanguage(p,"polish"),true);}
function renderCoverage(){const machine=new ServiceContextReferenceAntiphonUiState({runtimeMode:"memory",contextKey:"new",editable:true,serviceLanguage:"mixed"});machine.complete(machine.begin(),fixtures);const noops={onOpen:()=>undefined,onQueryChange:(_:string)=>undefined,onKeyDown:()=>undefined,onSelect:(_:ReferenceAntiphonRecord)=>undefined,onActiveIndexChange:(_:number)=>undefined,onClear:()=>undefined};const html=renderToStaticMarkup(<ServiceContextReferenceAntiphonFieldView editable selected={{id:"polish:1",displayNumber:"1",title:"Polska pierwsza"}} invalid open dirty={false} query="" snapshot={machine.snapshot()} activeIndex={2} {...noops}/>);assert.match(html,/aria-invalid="true"/);assert.match(html,/Polska pierwsza/);const control=html.match(/^<div class="service-antiphon-control[^>]*>[\s\S]*?<\/div>/)?.[0]??"";assert.doesNotMatch(control,/href=/);assert.match(html,/service-antiphon-option-active/);}
async function staticCoverage(){const [component,planning,css,contract,sync,candidate,migration]=await Promise.all([readFile("app/service-context-reference-antiphon-field.tsx","utf8"),readFile("app/planning-lifecycle-client.tsx","utf8"),readFile("app/globals.css","utf8"),readFile("src/application/reference-antiphon-contract.ts","utf8"),readFile("src/application/reference-antiphon-sync.ts","utf8"),readFile("src/application/reference-candidate-service.ts","utf8"),readFile("drizzle/0016_phase_31_18_bilingual_antiphons.sql","utf8")]);assert.match(component,/ArrowDown/);assert.match(component,/ArrowUp/);assert.match(component,/Home/);assert.match(component,/End/);assert.match(component,/Enter/);assert.match(component,/Escape/);assert.match(component,/onPointerDown=.*stopPropagation/);assert.match(component,/MemoryReferenceAntiphonClient/);assert.doesNotMatch(component,/Find antiphon|No antiphon selected|Remove antiphon|<h3>/);assert.doesNotMatch(planning,/>Candidate antiphon key</);assert.match(planning,/Selected antiphon must match the service language\./);assert.match(planning,/hasAntiphonLanguageMismatch/);assert.match(planning,/referenceAntiphons: new MemoryReferenceAntiphonProvider\(\)/);assert.match(css,/service-antiphon-listbox[\s\S]*direction: rtl/);assert.match(css,/max-height: min\(32rem, 70vh\)/);assert.match(contract,/sourceUrl\?: string/);assert.match(sync,/a\.language='czech'/);assert.match(candidate,/song\.id === data\.recommendedReferenceSongId/);assert.match(migration,/DELETE FROM "reference_antiphon_recommendations"/);assert.match(migration,/a\."language" <> s\."language"/);}
async function main(){await providerCoverage();languageCoverage();renderCoverage();await staticCoverage();console.log("Phase 31.18 bilingual-ready Service Context Antiphon lookup static/behavioral: PASS");}
void main().catch((error)=>{console.error(error);process.exitCode=1;});
