import assert from "node:assert/strict";
import { displayReferenceNumber, InMemoryReferenceCatalogProvider, normalizeReferenceNumberQuery, referenceCatalogRecords } from "../src/application/reference-catalog";

const catalog = new InMemoryReferenceCatalogProvider();
assert.equal(displayReferenceNumber(5210), "52/1");
assert.equal(displayReferenceNumber(3478), "347/8");
assert.equal(displayReferenceNumber(1100), "1/1");
assert.equal(displayReferenceNumber(298), "298");
assert.equal(displayReferenceNumber(955), "955");
assert.equal(normalizeReferenceNumberQuery("52/1"), 5210);
assert.equal(normalizeReferenceNumberQuery("347/8"), 3478);
assert.equal(normalizeReferenceNumberQuery("1/1"), 1100);
assert.equal(catalog.counts.czech, 808);
assert.equal(catalog.counts.polish, 990);
assert.equal(catalog.counts.all, 1798);
assert.equal(new Set(referenceCatalogRecords.map((r) => r.id)).size, 1798);
assert(referenceCatalogRecords.every((r) => !r.id.toLowerCase().includes("demo") && !r.id.toLowerCase().includes("synthetic") && !r.title.toLowerCase().includes("demo") && !r.title.toLowerCase().includes("synthetic")));
assert.deepEqual(catalog.list({ search: "5210", pageSize: 2000 }).records.map((r) => r.id), catalog.list({ search: "52/1", pageSize: 2000 }).records.map((r) => r.id));
assert.deepEqual(catalog.list({ search: "3478", pageSize: 2000 }).records.map((r) => r.id), catalog.list({ search: "347/8", pageSize: 2000 }).records.map((r) => r.id));
assert(catalog.list({ search: "298" }).records.some((r) => r.language === "czech" && r.title === "Otevři své srdce"));
assert(catalog.list({ search: "ŻEGNAMY" }).records.some((r) => r.language === "polish" && r.canonicalNumber === 955));
assert.equal(catalog.list({ language: "czech", pageSize: 2000 }).total, 808);
assert.equal(catalog.list({ language: "polish", pageSize: 2000 }).total, 990);
assert.equal(catalog.list({ language: "all", pageSize: 2000 }).total, 1798);
const orderedNumbers = catalog.list({ pageSize: 220 }).records.map((r) => r.canonicalNumber);
assert.deepEqual(orderedNumbers, [...orderedNumbers].sort((a, b) => a - b));
assert(orderedNumbers.indexOf(10) < orderedNumbers.indexOf(100), "numeric ordering places 10 before 100 rather than using lexicographic order");
const czech298 = catalog.list({ language: "czech", search: "298" }).records.find((r) => r.canonicalNumber === 298);
assert.equal(czech298?.title, "Otevři své srdce");
assert.equal(czech298?.sourceUrl, "https://www.evangelickykancional.cz/pisen/5593/otevri-sve-srdce");
const polish955 = catalog.list({ language: "polish", search: "955" }).records.find((r) => r.canonicalNumber === 955);
assert.equal(polish955?.title, "Żegnamy was w Bogu naszym");
assert.equal(polish955?.sourceUrl, "https://hymnary.org/hymn/SE2002/955");
assert.equal(referenceCatalogRecords.filter((r) => r.language === "czech" && !r.sourceUrl).length, 7);
assert.equal(referenceCatalogRecords.filter((r) => r.language === "polish" && r.sourceUrl).length, 990);
console.log("Reference catalog tests passed.");
