import assert from "node:assert/strict";import { createHash } from "node:crypto";import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";import { spawn } from "node:child_process";import { tmpdir } from "node:os";import { join } from "node:path";import { Pool } from "pg";import { POST } from "../app/api/reference-antiphons/route";import { DbReferenceAntiphonClient,MemoryReferenceAntiphonClient } from "../src/application/reference-antiphon-client";import { loadAndValidateReferenceAntiphons,synchronizeReferenceAntiphons } from "../src/application/reference-antiphon-sync";import { createDatabaseSql,createNpmInvocation,deriveControlUrl,deriveDatabaseUrl,dropDatabaseSql,generateE1DatabaseName,parseGuardDatabaseUrl,withCleanup } from "./engineering-e1-core";
const EXPECTED_REFERENCE_ANTIPHON_CHECK_CONSTRAINTS = [
  "reference_antiphons_id_matches_number",
  "reference_antiphons_id_non_empty",
  "reference_antiphons_number_positive",
  "reference_antiphons_source_url_valid",
  "reference_antiphons_title_non_empty",
] as const;
async function verifyCatalogLineEndingContract(bytes: Buffer): Promise<void> {
  const attributes = await readFile(".gitattributes", "utf8");
  assert.ok(attributes.split(/\r?\n/).includes("data/catalog/catalog-czech-antiphons.json text eol=lf"));
  const directory = await mkdtemp(join(tmpdir(), "organy-antiphons-"));
  try {
    const crlfPath = join(directory, "catalog-crlf.json");
    await writeFile(crlfPath, bytes.toString("utf8").replace(/\n/g, "\r\n"));
    assert.deepEqual(await loadAndValidateReferenceAntiphons(crlfPath), await loadAndValidateReferenceAntiphons());
    const mutatedPath = join(directory, "catalog-mutated.json");
    await writeFile(mutatedPath, bytes.toString("utf8").replace("Slavnostní introit", "Mutated introit"));
    await assert.rejects(() => loadAndValidateReferenceAntiphons(mutatedPath), /SHA-256 mismatch/);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}
const run=(name:string,url:string)=>new Promise<void>((resolve,reject)=>{const c=createNpmInvocation(process.execPath,process.env.npm_execpath,["run",name]);const p=spawn(c.command,c.args,{env:{...process.env,DATABASE_URL:url},stdio:"inherit"});p.on("error",reject);p.on("close",n=>n===0?resolve():reject(new Error(`${name} failed`)));});
async function fingerprint(pool:Pool){const tables=(await pool.query("select tablename from pg_tables where schemaname='public' order by tablename")).rows.map(r=>r.tablename);return JSON.stringify(await Promise.all(tables.map(async t=>[t,(await pool.query(`select count(*)::int n from ${t}`)).rows[0].n])));}
async function invoke(action:string,input:unknown){const r=await POST(new Request("http://localhost/api/reference-antiphons",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,input})}));return{status:r.status,body:await r.json()};}
async function main(){if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is required for Phase 31.9 verification.");const guardUrl=process.env.DATABASE_URL,guard=parseGuardDatabaseUrl(guardUrl),control=new Pool({connectionString:deriveControlUrl(guard)}),guardPool=new Pool({connectionString:guardUrl}),before=await fingerprint(guardPool);await guardPool.end();const name=generateE1DatabaseName(),url=deriveDatabaseUrl(guard,name);await control.query(createDatabaseSql(name));const runtime=process.env.ORGANY_RUNTIME;
try{await withCleanup(async()=>{await run("db:migrate",url);await run("db:migrate",url);const pool=new Pool({connectionString:url});try{
 const columns=await pool.query("select column_name,is_nullable from information_schema.columns where table_name='reference_antiphons' order by ordinal_position");assert.deepEqual(columns.rows.map(r=>r.column_name),["id","language","canonical_number","title","source_url"]);assert.ok(columns.rows.every(r=>r.is_nullable==='NO'));const constraints=await pool.query("select constraint_type from information_schema.table_constraints where table_schema='public' and table_name='reference_antiphons'");assert.equal(constraints.rows.filter(r=>r.constraint_type==='PRIMARY KEY').length,1);const applicationChecks=await pool.query("select conname from pg_constraint where conrelid='public.reference_antiphons'::regclass and contype='c' and conname=any($1::text[]) order by conname",[EXPECTED_REFERENCE_ANTIPHON_CHECK_CONSTRAINTS]);assert.deepEqual(applicationChecks.rows.map(r=>r.conname),[...EXPECTED_REFERENCE_ANTIPHON_CHECK_CONSTRAINTS].sort());assert.match(String((await pool.query("select indexdef from pg_indexes where indexname='reference_antiphons_language_canonical_number_idx'")).rows[0].indexdef),/UNIQUE/);
 const bytes=await readFile("data/catalog/catalog-czech-antiphons.json"),records=await loadAndValidateReferenceAntiphons();assert.equal(createHash("sha256").update(bytes.toString("utf8").replace(/\r\n/g, "\n")).digest("hex"),"9fe6f782ad62afa2d664fcb480a039a9b5dacf4bc193decb92a41d85023414e8");await verifyCatalogLineEndingContract(bytes);assert.equal(records.length,116);assert.deepEqual([records[0].canonicalNumber,records[58].canonicalNumber,records.at(-1)!.canonicalNumber],[800,858,915]);
 assert.deepEqual(await synchronizeReferenceAntiphons(pool),{czech:116,polish:0,total:116});const snapshot=JSON.stringify((await pool.query("select * from reference_antiphons order by canonical_number")).rows);assert.deepEqual(await synchronizeReferenceAntiphons(pool),{czech:116,polish:0,total:116});assert.equal(JSON.stringify((await pool.query("select * from reference_antiphons order by canonical_number")).rows),snapshot);
 await pool.query("create table phase_31_9_scope_guard(id int);insert into phase_31_9_scope_guard values(1);insert into reference_antiphons values('czech:999','czech',999,'stale','https://www.evangelickykancional.cz/stale')");await synchronizeReferenceAntiphons(pool);assert.equal((await pool.query("select count(*)::int n from reference_antiphons where id='czech:999'")).rows[0].n,0);assert.equal((await pool.query("select count(*)::int n from phase_31_9_scope_guard")).rows[0].n,1);
 const rollback=JSON.stringify((await pool.query("select * from reference_antiphons order by canonical_number")).rows);await assert.rejects(()=>synchronizeReferenceAntiphons(pool,{records:records.map((r,i)=>i? r:{...r,title:'must roll back'}),failBeforeCommit:true}));assert.equal(JSON.stringify((await pool.query("select * from reference_antiphons order by canonical_number")).rows),rollback);
 process.env.DATABASE_URL=url;process.env.ORGANY_RUNTIME="db";const client=new DbReferenceAntiphonClient(async(a,i)=>(await invoke(a,i)).body),all=await client.list({language:"all",pageSize:200});assert.deepEqual(all.counts,{all:116,czech:116,polish:0});assert.deepEqual([all.records[0].canonicalNumber,all.records[58].canonicalNumber,all.records.at(-1)!.canonicalNumber],[800,858,915]);assert.equal((await client.list({search:"858"})).records[0].canonicalNumber,858);assert.ok((await client.list({search:"trojici"})).records.some(r=>r.canonicalNumber===858));assert.deepEqual((await client.list({page:1,pageSize:10})).records.map(r=>r.canonicalNumber),[810,811,812,813,814,815,816,817,818,819]);assert.equal((await client.getById("czech:915"))?.canonicalNumber,915);
 await pool.query("update reference_antiphons set title='DB-only title' where id='czech:858'");assert.equal((await client.getById("czech:858"))?.title,"DB-only title");assert.notEqual((await new MemoryReferenceAntiphonClient().getById("czech:858"))?.title,"DB-only title");assert.equal((await invoke("getById",{id:"czech:999"})).status,400);await pool.query("delete from reference_antiphons where id='czech:915'");assert.equal((await invoke("getById",{id:"czech:915"})).status,404);assert.deepEqual(await synchronizeReferenceAntiphons(pool),{czech:116,polish:0,total:116});assert.deepEqual(await client.getById("czech:915"),{id:"czech:915",language:"czech",canonicalNumber:915,displayNumber:"915",title:"Pohřební bohoslužba (Pohřeb dítěte)",sourceUrl:"https://www.evangelickykancional.cz/pisen/7039/pohrebni-bohosluzba-pohreb-ditete"});for(const [a,i] of [["mutate",{}],["list",{extra:true}],["getById",{id:"bad"}]] as Array<[string,unknown]>)assert.equal((await invoke(a,i)).status,400);const malformed=await POST(new Request("http://x",{method:"POST",body:"{"}));assert.equal(malformed.status,400);delete process.env.DATABASE_URL;assert.equal((await invoke("list",{})).status,500);
}finally{await pool.end();}},async()=>{const [terminate,drop]=dropDatabaseSql(name);await control.query(terminate,[name]);await control.query(drop);});assert.equal((await control.query("select 1 from pg_database where datname=$1",[name])).rows.length,0);const afterPool=new Pool({connectionString:guardUrl});assert.equal(await fingerprint(afterPool),before);await afterPool.end();console.log("Phase 31.9 authoritative reference antiphons: PASS");}finally{process.env.DATABASE_URL=guardUrl;if(runtime===undefined)delete process.env.ORGANY_RUNTIME;else process.env.ORGANY_RUNTIME=runtime;await control.end();}}
void main().catch(e=>{console.error("Phase 31.9 authoritative reference antiphons: FAIL");console.error(e);process.exitCode=1;});
