import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { Pool } from "pg";
import { POST } from "../app/api/interaction/route";
import { DbInteractionClient, type InteractionTransport } from "../app/planning-lifecycle-client";
import { seedDemoInteractionKnowledge } from "../src/application/interaction-seed";
import { ReferenceAntiphonRecommendationRequestState } from "../src/application/reference-antiphon-recommendation-request-state";
import type { ReferenceAntiphonRecommendation } from "../src/application/reference-antiphon-recommendation";
import { createDatabaseSql, createNpmInvocation, deriveControlUrl, deriveDatabaseUrl, dropDatabaseSql, generateE1DatabaseName, parseGuardDatabaseUrl, withCleanup } from "./engineering-e1-core";
const PASS="Phase 31.10 authoritative reference antiphon recommendation: PASS";
type Actor={userId:string;role:string}; type Response={status:number;body:any};
const run=(name:string,url:string)=>new Promise<void>((resolve,reject)=>{const c=createNpmInvocation(process.execPath,process.env.npm_execpath,["run",name]);const p=spawn(c.command,c.args,{env:{...process.env,DATABASE_URL:url},stdio:"inherit"});p.on("error",reject);p.on("close",code=>code===0?resolve():reject(new Error(`${name} failed (${code})`)));});
async function invoke(action:string,input:unknown,actor:unknown):Promise<Response>{const response=await POST(new Request("http://localhost/api/interaction",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,input,actor})}));return{status:response.status,body:await response.json()};}
async function fingerprint(pool:Pool){const tables=(await pool.query("select tablename from pg_tables where schemaname='public' order by tablename")).rows.map(r=>String(r.tablename));return JSON.stringify(await Promise.all(tables.map(async table=>[table,(await pool.query(`select count(*)::int count from ${table}`)).rows[0].count])));}
async function unchangedSnapshot(pool:Pool){const tables=["antiphon_mappings","service_contexts","song_preferences","reference_song_preferences","reference_organist_repertoire","reference_melody_classes","reference_song_melody_memberships","planning_sets","completed_service_records"];const existing=new Set((await pool.query("select tablename from pg_tables where schemaname=\'public\'")).rows.map(r=>String(r.tablename)));return JSON.stringify(await Promise.all(tables.filter(t=>existing.has(t)).map(async t=>[t,(await pool.query(`select coalesce(json_agg(x order by row_to_json(x)::text),\'[]\'::json) value from ${t} x`)).rows[0].value])));}
const exactNull=(id:string):ReferenceAntiphonRecommendation=>({antiphonId:id,recommendedSong:null});
const exactSong=(id:string,songId:string,language:"czech"|"polish",canonicalNumber:number,displayNumber:string,title:string):ReferenceAntiphonRecommendation=>({antiphonId:id,recommendedSong:{referenceSongId:songId,language,canonicalNumber,displayNumber,title}});
async function staleBrowserTransport(admin:Actor){type Pending={resolve:(value:any)=>void;actual:Promise<Response>};const pending:Pending[]=[];const transport:InteractionTransport=(action,input,actor)=>new Promise(resolve=>pending.push({resolve,actual:invoke(action,input,actor)})) as any;const browser=new DbInteractionClient(transport),state=new ReferenceAntiphonRecommendationRequestState();let shown:ReferenceAntiphonRecommendation|null=null;const oldToken=state.begin(),old=browser.getReferenceAntiphonRecommendation({actor:admin as any,antiphonId:"czech:800"});const newerToken=state.begin(),newer=browser.getReferenceAntiphonRecommendation({actor:admin as any,antiphonId:"czech:801"});const [oldActual,newActual]=await Promise.all(pending.map(item=>item.actual));pending[1].resolve(newActual.body);const newResult=await newer;if(newResult.success)state.complete(newerToken,newResult.value,value=>{shown=value;});pending[0].resolve(oldActual.body);const oldResult=await old;if(oldResult.success)state.complete(oldToken,oldResult.value,value=>{shown=value;});assert.ok(shown);assert.equal((shown as ReferenceAntiphonRecommendation).antiphonId,"czech:801");}
async function main(){if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is required for Phase 31.10 verification.");const guardUrl=process.env.DATABASE_URL,guard=parseGuardDatabaseUrl(guardUrl),guardPool=new Pool({connectionString:guardUrl}),before=await fingerprint(guardPool);await guardPool.end();const control=new Pool({connectionString:deriveControlUrl(guard)}),name=generateE1DatabaseName(),url=deriveDatabaseUrl(guard,name);await control.query(createDatabaseSql(name));const runtime=process.env.ORGANY_RUNTIME;let firstSong:any,secondSong:any,unrelatedBefore:string;
try{await withCleanup(async()=>{await run("db:migrate",url);await run("db:migrate",url);await run("db:sync:reference-catalog",url);await run("db:sync:reference-antiphons",url);const pool=new Pool({connectionString:url});try{const columns=await pool.query("select column_name,is_nullable,column_default,data_type from information_schema.columns where table_name='reference_antiphon_recommendations' order by ordinal_position");assert.deepEqual(columns.rows.map(r=>r.column_name),["antiphon_id","reference_song_id","updated_at"]);assert.ok(columns.rows.every(r=>r.is_nullable==='NO'));assert.ok(columns.rows[2].column_default);const constraints=await pool.query("select constraint_type from information_schema.table_constraints where table_name='reference_antiphon_recommendations'");assert.equal(constraints.rows.filter(r=>r.constraint_type==='PRIMARY KEY').length,1);assert.equal(constraints.rows.filter(r=>r.constraint_type==='FOREIGN KEY').length,2);assert.deepEqual((await pool.query("select rc.delete_rule from information_schema.referential_constraints rc join information_schema.table_constraints tc on tc.constraint_name=rc.constraint_name where tc.table_name='reference_antiphon_recommendations' order by tc.constraint_name")).rows,[{delete_rule:"CASCADE"},{delete_rule:"CASCADE"}]);assert.match(String((await pool.query("select indexdef from pg_indexes where indexname='reference_antiphon_recommendations_song_idx'")).rows[0].indexdef),/reference_song_id/);await seedDemoInteractionKnowledge(pool);const songs=(await pool.query("select id,language,canonical_number,title from reference_catalog_songs order by language,canonical_number limit 2")).rows;assert.equal(songs.length,2);[firstSong,secondSong]=songs;unrelatedBefore=await unchangedSnapshot(pool);}finally{await pool.end();}
process.env.DATABASE_URL=url;process.env.ORGANY_RUNTIME="db";const roles:Actor[]=[{userId:"demo-priest-user",role:"priest"},{userId:"demo-organist-user",role:"organist"},{userId:"demo-admin-user",role:"admin"},{userId:"demo-member-user",role:"congregationMember"}],admin=roles[2];for(const actor of roles){const r=await invoke("getReferenceAntiphonRecommendation",{antiphonId:"czech:800"},actor);assert.equal(r.status,200);assert.deepEqual(r.body.value,exactNull("czech:800"));}
let r=await invoke("setReferenceAntiphonRecommendation",{antiphonId:"czech:800",referenceSongId:firstSong.id},admin);assert.equal(r.status,200);assert.deepEqual(r.body.value,exactSong("czech:800",firstSong.id,firstSong.language,Number(firstSong.canonical_number),r.body.value.recommendedSong.displayNumber,firstSong.title));assert.deepEqual((await invoke("getReferenceAntiphonRecommendation",{antiphonId:"czech:800"},roles[0])).body.value,r.body.value);
r=await invoke("setReferenceAntiphonRecommendation",{antiphonId:"czech:800",referenceSongId:secondSong.id},admin);assert.equal(r.status,200);assert.equal(r.body.value.recommendedSong.referenceSongId,secondSong.id);r=await invoke("setReferenceAntiphonRecommendation",{antiphonId:"czech:800",referenceSongId:null},admin);assert.deepEqual(r.body.value,exactNull("czech:800"));
for(const actor of [roles[0],roles[1],roles[3]])assert.equal((await invoke("setReferenceAntiphonRecommendation",{antiphonId:"czech:800",referenceSongId:"czech:1"},actor)).status,403);for(const [action,input] of [["getReferenceAntiphonRecommendation",{}],["getReferenceAntiphonRecommendation",{antiphonId:"czech:999"}],["setReferenceAntiphonRecommendation",{antiphonId:"czech:999",referenceSongId:"czech:1"}],["setReferenceAntiphonRecommendation",{antiphonId:"czech:800",referenceSongId:"bad"}]] as const)assert.equal((await invoke(action,input,admin)).status,400);assert.equal((await invoke("getReferenceAntiphonRecommendation",{antiphonId:"polish:800"},admin)).status,400);assert.equal((await invoke("setReferenceAntiphonRecommendation",{antiphonId:"polish:800",referenceSongId:null},admin)).status,400);const missingDb=new Pool({connectionString:url});try{await missingDb.query("delete from reference_antiphons where id=\'czech:915\'");}finally{await missingDb.end();}assert.equal((await invoke("getReferenceAntiphonRecommendation",{antiphonId:"czech:915"},admin)).status,404);await run("db:sync:reference-antiphons",url);assert.deepEqual((await invoke("getReferenceAntiphonRecommendation",{antiphonId:"czech:915"},admin)).body.value,exactNull("czech:915"));assert.equal((await invoke("setReferenceAntiphonRecommendation",{antiphonId:"czech:800",referenceSongId:"czech:999999"},admin)).status,404);
await invoke("setReferenceAntiphonRecommendation",{antiphonId:"czech:800",referenceSongId:firstSong.id},admin);const db=new Pool({connectionString:url});try{await db.query("create function reject_recommendation() returns trigger language plpgsql as $$begin raise exception 'injected';end$$;create trigger reject_recommendation before update on reference_antiphon_recommendations for each row execute function reject_recommendation()");assert.equal((await invoke("setReferenceAntiphonRecommendation",{antiphonId:"czech:800",referenceSongId:secondSong.id},admin)).status,500);await db.query("drop trigger reject_recommendation on reference_antiphon_recommendations;drop function reject_recommendation()");}finally{await db.end();}assert.equal((await invoke("getReferenceAntiphonRecommendation",{antiphonId:"czech:800"},admin)).body.value.recommendedSong.referenceSongId,firstSong.id);await staleBrowserTransport(admin);
const competing=await Promise.all([invoke("setReferenceAntiphonRecommendation",{antiphonId:"czech:801",referenceSongId:firstSong.id},admin),invoke("setReferenceAntiphonRecommendation",{antiphonId:"czech:801",referenceSongId:secondSong.id},admin)]);assert.ok(competing.every(result=>result.status===200));const concurrent=(await invoke("getReferenceAntiphonRecommendation",{antiphonId:"czech:801"},admin)).body.value;assert.ok([firstSong.id,secondSong.id].includes(concurrent.recommendedSong.referenceSongId));const cascadeDb=new Pool({connectionString:url});try{await cascadeDb.query("begin");await cascadeDb.query("delete from reference_catalog_songs where id=$1",[concurrent.recommendedSong.referenceSongId]);assert.equal(Number((await cascadeDb.query("select count(*) n from reference_antiphon_recommendations where antiphon_id=\'czech:801\'")).rows[0].n),0);await cascadeDb.query("rollback");await cascadeDb.query("begin");await cascadeDb.query("delete from reference_antiphons where id=\'czech:801\'");assert.equal(Number((await cascadeDb.query("select count(*) n from reference_antiphon_recommendations where antiphon_id=\'czech:801\'")).rows[0].n),0);await cascadeDb.query("rollback");}finally{await cascadeDb.end();}await run("db:sync:reference-catalog",url);await run("db:sync:reference-catalog",url);await run("db:sync:reference-antiphons",url);await run("db:sync:reference-antiphons",url);const finalDb=new Pool({connectionString:url});try{assert.equal(await unchangedSnapshot(finalDb),unrelatedBefore);assert.equal(Number((await finalDb.query("select count(*) n from reference_antiphon_recommendations where antiphon_id=\'czech:801\'")).rows[0].n),1);}finally{await finalDb.end();}
},async()=>{const[terminate,drop]=dropDatabaseSql(name);await control.query(terminate,[name]);await control.query(drop);});assert.equal((await control.query("select 1 from pg_database where datname=$1",[name])).rows.length,0);const afterPool=new Pool({connectionString:guardUrl});assert.equal(await fingerprint(afterPool),before);await afterPool.end();console.log(PASS);}finally{process.env.DATABASE_URL=guardUrl;if(runtime===undefined)delete process.env.ORGANY_RUNTIME;else process.env.ORGANY_RUNTIME=runtime;await control.end();}}
void main().catch(error=>{console.error(error);process.exitCode=1;});
