import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { Pool } from "pg";
import { PostgresReferenceAntiphonProvider } from "../src/application/postgres-reference-antiphon";
import { PgReferenceAntiphonRecommendationRepository } from "../src/application/reference-antiphon-recommendation";
import { synchronizeReferenceAntiphons } from "../src/application/reference-antiphon-sync";
import { synchronizeReferenceCatalog } from "../src/application/reference-catalog-sync";
import { createDatabaseSql,createNpmInvocation,deriveControlUrl,deriveDatabaseUrl,dropDatabaseSql,generateE1DatabaseName,parseGuardDatabaseUrl,withCleanup } from "./engineering-e1-core";
const PASS="Phase 31.18 bilingual-ready Service Context Antiphon lookup: PASS";
const run=(name:string,url:string)=>new Promise<void>((resolve,reject)=>{const c=createNpmInvocation(process.execPath,process.env.npm_execpath,["run",name]);const p=spawn(c.command,c.args,{env:{...process.env,DATABASE_URL:url},stdio:"inherit"});p.on("error",reject);p.on("close",n=>n===0?resolve():reject(new Error(`${name} failed`)));});
async function main(){if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is required for Phase 31.18 verification.");const guard=parseGuardDatabaseUrl(process.env.DATABASE_URL),control=new Pool({connectionString:deriveControlUrl(guard)}),name=generateE1DatabaseName(),url=deriveDatabaseUrl(guard,name);await control.query(createDatabaseSql(name));try{await withCleanup(async()=>{await run("db:migrate",url);await run("db:migrate",url);const pool=new Pool({connectionString:url});try{
 const sourceColumn=(await pool.query("select is_nullable from information_schema.columns where table_schema='public' and table_name='reference_antiphons' and column_name='source_url'")).rows[0];assert.equal(sourceColumn.is_nullable,"YES");
 await pool.query("insert into reference_antiphons(id,language,canonical_number,title,source_url) values('polish:1','polish',1,'Polska pierwsza',null)");
 await assert.rejects(()=>pool.query("insert into reference_antiphons(id,language,canonical_number,title,source_url) values('czech:999','czech',999,'Bad Czech',null)"));
 await assert.rejects(()=>pool.query("insert into reference_antiphons(id,language,canonical_number,title,source_url) values('polish:2','polish',2,'Bad Polish','http://bad')"));
 const counts=await synchronizeReferenceAntiphons(pool);assert.deepEqual(counts,{czech:116,polish:1,total:117});assert.equal(Number((await pool.query("select count(*) n from reference_antiphons where id='polish:1'")).rows[0].n),1,"Czech sync deleted Polish fixture");
 const provider=new PostgresReferenceAntiphonProvider(pool),all=await provider.list({language:"all",pageSize:200});assert.equal(all.records[0].id,"polish:1");assert.equal(all.records.at(-1)?.id,"czech:915");assert.deepEqual((await provider.list({language:"polish"})).records.map(r=>r.id),["polish:1"]);assert.deepEqual((await provider.list({search:"80",pageSize:200})).records.slice(0,2).map(r=>r.id),["czech:800","czech:801"]);
 await synchronizeReferenceCatalog(pool);const repo=new PgReferenceAntiphonRecommendationRepository(pool);assert.equal((await repo.set("czech:800","czech:1")).kind,"ok");assert.equal((await repo.set("czech:800","polish:1")).kind,"languageMismatch");assert.equal((await repo.get("czech:800"))?.recommendedSong?.referenceSongId,"czech:1");assert.equal((await repo.set("polish:1","polish:1")).kind,"ok");assert.equal((await repo.set("polish:1","czech:1")).kind,"languageMismatch");assert.equal((await repo.get("polish:1"))?.recommendedSong?.referenceSongId,"polish:1");
 await pool.query(`insert into service_contexts(service_date,service_time,service_language,priest_display_name,organist_display_name,reference_antiphon_id,reference_antiphon_display_number,reference_antiphon_title,reference_antiphon_source_url) values('2026-08-09','10:00','polish','P','O','polish:1','1','Polska pierwsza',null)`);const snapshot=(await pool.query("select reference_antiphon_id,reference_antiphon_display_number,reference_antiphon_title,reference_antiphon_source_url from service_contexts order by id desc limit 1")).rows[0];assert.deepEqual(snapshot,{reference_antiphon_id:'polish:1',reference_antiphon_display_number:'1',reference_antiphon_title:'Polska pierwsza',reference_antiphon_source_url:null});
 }finally{await pool.end();}},async()=>{const [terminate,drop]=dropDatabaseSql(name);await control.query(terminate,[name]);await control.query(drop);});console.log(PASS);}finally{await control.end();}}
void main().catch((error)=>{console.error("Phase 31.18 bilingual-ready Service Context Antiphon lookup: FAIL");console.error(error);process.exitCode=1;});
