import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import { Pool } from "pg";
import { POST } from "../app/api/interaction/route";
import { DbInteractionClient } from "../app/planning-lifecycle-client";
import { DbReferenceCatalogClient } from "../src/application/reference-catalog-client";
import { seedDemoInteractionKnowledge } from "../src/application/interaction-seed";
import { loadAndValidateReferenceCatalog, synchronizeReferenceCatalog } from "../src/application/reference-catalog-sync";
import { PgReferenceMelodyRepository } from "../src/application/reference-melody";
import { ReferencePreferenceRequestTracker } from "../src/application/reference-preference-request-tracker";
import { createDatabaseSql, createNpmInvocation, deriveControlUrl, deriveDatabaseUrl, dropDatabaseSql, generateE1DatabaseName, parseGuardDatabaseUrl, withCleanup } from "./engineering-e1-core";

type Result = { status: number; body: any }; type Actor = { userId: string; role?: any };
const GET = "getReferenceMelodyClass", MERGE = "mergeReferenceMelodyClasses";
const run = (name: string, url: string) => new Promise<void>((resolve, reject) => { const command = createNpmInvocation(process.execPath, process.env.npm_execpath, ["run", name]); const child = spawn(command.command, command.args, { env: { ...process.env, DATABASE_URL: url }, stdio: "inherit" }); child.on("error", reject); child.on("close", (code) => code === 0 ? resolve() : reject(new Error(`${name} failed (${code})`))); });
async function invoke(action: string, input: unknown, actor: unknown): Promise<Result> { const response = await POST(new Request("http://localhost/api/interaction", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, input, actor }) })); return { status: response.status, body: await response.json() }; }
const fingerprint = async (pool: Pool) => JSON.stringify((await pool.query("select datname from pg_database where datname=current_database()")).rows);
function exact(value: any, anchor: string, size?: number) { assert.deepEqual(Object.keys(value).sort(), ["classId", "members", "referenceSongId"]); assert.equal(value.referenceSongId, anchor); if (size !== undefined) assert.equal(value.members.length, size); const ids = new Set<string>(); for (const member of value.members) { assert.deepEqual(Object.keys(member).sort(), ["canonicalNumber", "displayNumber", "language", "referenceSongId", "title"]); assert.ok(!ids.has(member.referenceSongId)); ids.add(member.referenceSongId); } }
async function error(action: string, input: unknown, actor: unknown, code: string) { const result = await invoke(action, input, actor); assert.equal(result.body.error?.code, code, `${action}: ${JSON.stringify(result.body)}`); }
type Deferred = { actual: Promise<Result>; resolve(value: unknown): void };
async function stale(label: string, older: (client: DbInteractionClient) => Promise<any>, newer: (client: DbInteractionClient) => Promise<any>, between: () => void = () => undefined) { const pending: Deferred[]=[]; const client=new DbInteractionClient(((action:string,input:unknown,actor?:Actor)=>new Promise((resolve)=>pending.push({actual:invoke(action,input,actor),resolve}))) as any); const tracker=new ReferencePreferenceRequestTracker(); const applied:any[]=[]; const oldToken=tracker.begin(); const oldPromise=older(client); const oldActual=await pending[0].actual; between(); const newToken=tracker.begin(); const newPromise=newer(client); const newActual=await pending[1].actual; pending[1].resolve(newActual.body); const current=await newPromise; if(tracker.isCurrent(newToken)) applied.push(current); pending[0].resolve(oldActual.body); const obsolete=await oldPromise; if(tracker.isCurrent(oldToken)) applied.push(obsolete); assert.equal(applied.length,1,`${label} allowed stale response`); }

async function main() {
 if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required for Phase 31.8 verification.");
 const guardUrl=process.env.DATABASE_URL, guard=parseGuardDatabaseUrl(guardUrl), control=new Pool({connectionString:deriveControlUrl(guard)}), before=await fingerprint(new Pool({connectionString:guardUrl})); const name=generateE1DatabaseName(); await control.query(createDatabaseSql(name)); const url=deriveDatabaseUrl(guard,name), oldRuntime=process.env.ORGANY_RUNTIME;
 try { await withCleanup(async()=>{
  await run("db:migrate",url); await run("db:sync:reference-catalog",url); process.env.DATABASE_URL=url; process.env.ORGANY_RUNTIME="db"; const db=new Pool({connectionString:url});
  try {
   // 1-3: full schema, constraints, index, counts, and one membership per song.
   const columns=await db.query("select table_name,column_name,is_nullable,column_default,data_type from information_schema.columns where table_name in ('reference_melody_classes','reference_song_melody_memberships') order by table_name,ordinal_position"); assert.equal(columns.rows.length,6); assert.ok(columns.rows.every(r=>r.is_nullable==='NO')); assert.ok(columns.rows.filter(r=>String(r.column_name).endsWith('_at')).every(r=>String(r.data_type).includes('timestamp')&&r.column_default));
   const constraints=await db.query("select table_name,constraint_type from information_schema.table_constraints where table_name in ('reference_melody_classes','reference_song_melody_memberships')"); assert.equal(constraints.rows.filter(r=>r.constraint_type==='PRIMARY KEY').length,2); assert.equal(constraints.rows.filter(r=>r.constraint_type==='FOREIGN KEY').length,2);
   assert.match(String((await db.query("select indexdef from pg_indexes where indexname='reference_song_melody_memberships_class_id_idx'")).rows[0].indexdef),/class_id/);
   assert.deepEqual((await db.query("select (select count(*)::int from reference_catalog_songs) songs,(select count(*)::int from reference_song_melody_memberships) memberships,(select count(*)::int from reference_melody_classes) classes,(select count(*)::int from (select c.id from reference_melody_classes c join reference_song_melody_memberships m on m.class_id=c.id group by c.id having count(*)<>1)x) non_singletons")).rows[0],{songs:1798,memberships:1798,classes:1798,non_singletons:0});
   await seedDemoInteractionKnowledge(db); await db.query("insert into app_user_roles(user_id,role) values ('demo-organist-user','admin') on conflict do nothing");
  } finally { await db.end(); }
  const roles:Actor[]=[{userId:'demo-priest-user',role:'priest'},{userId:'demo-organist-user',role:'organist'},{userId:'demo-admin-user',role:'admin'},{userId:'demo-member-user',role:'congregationMember'}], admin=roles[2];
  // 4-14: exact DTO, ordering, every role, permission and complete structured validation.
  for(const actor of roles){const r=await invoke(GET,{referenceSongId:'czech:1'},actor);assert.equal(r.status,200);exact(r.body.value,'czech:1',1);}
  for(const actor of [roles[0],roles[1],roles[3]]) await error(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:2'},actor,'permissionDenied');
  for(const input of [null,{}, {referenceSongId:1},{referenceSongId:'czech:1',extra:true}]) await error(GET,input,admin,'invalidInput');
  for(const input of [null,{}, {referenceSongId:'czech:1'}, {referenceSongId:'czech:1',mergeWithReferenceSongId:2},{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:2',extra:true}]) await error(MERGE,input,admin,'invalidInput');
  for(const actor of [null,{}, {userId:''},{userId:'demo-admin-user',role:'bad'},{userId:'demo-admin-user',role:'admin',extra:true}]) { await error(GET,{referenceSongId:'czech:1'},actor,'invalidInput'); await error(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:2'},actor,'invalidInput'); }
  for(const actor of [{userId:'missing',role:'admin'},{userId:'demo-priest-user',role:'admin'}]) { await error(GET,{referenceSongId:'czech:1'},actor,'permissionDenied'); await error(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:2'},actor,'permissionDenied'); }
  await error(GET,{referenceSongId:'czech:999999'},admin,'notFound'); await error(MERGE,{referenceSongId:'czech:999999',mergeWithReferenceSongId:'czech:1'},admin,'notFound'); await error(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:999999'},admin,'notFound');
  const self=await invoke(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:1'},admin); exact(self.body.value,'czech:1',1);
  const pair=await invoke(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:2'},admin); exact(pair.body.value,'czech:1',2); assert.equal(pair.body.value.classId,'reference-melody:czech:1'); assert.deepEqual((await invoke(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:2'},admin)).body.value,pair.body.value);
  await invoke(MERGE,{referenceSongId:'czech:3',mergeWithReferenceSongId:'czech:4'},admin); const multi=await invoke(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:3'},admin); exact(multi.body.value,'czech:1',4); assert.deepEqual(multi.body.value.members.map((m:any)=>m.canonicalNumber),[1,2,3,4]);
  // 15-16: injected rollback and genuinely overlapping concurrent merges.
  let direct=new Pool({connectionString:url}); try { const failing=new PgReferenceMelodyRepository(direct,{failAfterMembershipMove:true}); await assert.rejects(()=>failing.mergeReferenceMelodyClasses('czech:5','czech:6')); assert.equal((await failing.getReferenceMelodyClass('czech:5'))!.members.length,1); } finally { await direct.end(); }
  await Promise.all([invoke(MERGE,{referenceSongId:'czech:7',mergeWithReferenceSongId:'czech:8'},admin),invoke(MERGE,{referenceSongId:'czech:9',mergeWithReferenceSongId:'czech:8'},admin)]); direct=new Pool({connectionString:url}); try { const state=await direct.query("select (select count(*)::int from reference_song_melody_memberships) memberships,(select count(*)::int from reference_song_melody_memberships m left join reference_melody_classes c on c.id=m.class_id where c.id is null) dangling,(select count(*)::int from reference_melody_classes c left join reference_song_melody_memberships m on m.class_id=c.id where m.class_id is null) orphans,(select count(*)::int from (select reference_song_id from reference_song_melody_memberships group by reference_song_id having count(*)>1)x) duplicates"); assert.deepEqual(state.rows[0],{memberships:1798,dangling:0,orphans:0,duplicates:0}); } finally { await direct.end(); }
  // 17-19: reconcile seam proves dependent preservation, add/remove cleanup and rollback without touching JSON.
  const frozen=await loadAndValidateReferenceCatalog(), removed=frozen.at(-1)!, synthetic={...removed,id:`${removed.language}:999999`,canonicalNumber:999999,sourceId:'phase-31-8-test',title:'Acceptance-only song',sourceUrl:null}, derived=[...frozen.slice(0,-1),synthetic]; direct=new Pool({connectionString:url}); try { await direct.query("insert into reference_song_preferences(profile_id,reference_song_id,score) values ('pref-priest','czech:1',2) on conflict do nothing; insert into reference_organist_repertoire(organist_person_id,reference_song_id) values ('demo-organist','czech:1') on conflict do nothing"); await synchronizeReferenceCatalog(direct,{records:derived,expectedCounts:{czech:808,polish:990,total:1798}}); assert.deepEqual((await direct.query("select (select count(*)::int from reference_song_preferences where reference_song_id='czech:1') preference,(select count(*)::int from reference_organist_repertoire where reference_song_id='czech:1') repertoire,(select count(*)::int from reference_song_melody_memberships where reference_song_id='czech:1') melody,(select count(*)::int from reference_song_melody_memberships where reference_song_id=$2 and class_id=$3) added,(select count(*)::int from reference_catalog_songs where id=$1) removed",[removed.id,synthetic.id,`reference-melody:${synthetic.id}`])).rows[0],{preference:1,repertoire:1,melody:1,added:1,removed:0}); const snap=JSON.stringify((await direct.query("select id from reference_catalog_songs order by id")).rows); await assert.rejects(()=>synchronizeReferenceCatalog(direct,{records:frozen,failBeforeCommit:true})); assert.equal(JSON.stringify((await direct.query("select id from reference_catalog_songs order by id")).rows),snap); await synchronizeReferenceCatalog(direct); } finally { await direct.end(); }
  // 20 and 22: actual browser DB client and genuinely deferred transport in reverse order.
  const browser=new DbInteractionClient(async(action: string,input: unknown,actor?: Actor)=>(await invoke(action,input,actor)).body); exact((await browser.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:1'})).value,'czech:1',4); exact((await browser.mergeReferenceMelodyClasses({actor:admin as any,referenceSongId:'czech:10',mergeWithReferenceSongId:'czech:11'})).value,'czech:10',2);
  await stale('song',c=>c.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:1'}),c=>c.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:10'})); await stale('actor',c=>c.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:1'}),c=>c.getReferenceMelodyClass({actor:roles[0] as any,referenceSongId:'czech:1'})); await stale('role',c=>c.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:1'}),c=>c.getReferenceMelodyClass({actor:{userId:'demo-admin-user'} as any,referenceSongId:'czech:1'})); process.env.ORGANY_RUNTIME='db'; await stale('runtime',c=>c.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:1'}),c=>c.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:1'}),()=>{process.env.ORGANY_RUNTIME='memory';}); process.env.ORGANY_RUNTIME='db'; await stale('merge target',c=>c.mergeReferenceMelodyClasses({actor:admin as any,referenceSongId:'czech:15',mergeWithReferenceSongId:'czech:16'}),c=>c.mergeReferenceMelodyClasses({actor:admin as any,referenceSongId:'czech:15',mergeWithReferenceSongId:'czech:17'})); await stale('competing merge',c=>c.mergeReferenceMelodyClasses({actor:admin as any,referenceSongId:'czech:12',mergeWithReferenceSongId:'czech:13'}),c=>c.mergeReferenceMelodyClasses({actor:admin as any,referenceSongId:'czech:12',mergeWithReferenceSongId:'czech:14'}));
  const pending:any[]=[]; const catalog=new DbReferenceCatalogClient(((action: "list" | "getById",input: unknown)=>new Promise(resolve=>pending.push({action,input,resolve}))) as any); const tracker=new ReferencePreferenceRequestTracker(); const a=tracker.begin(), oldSearch=catalog.list({search:'1'}), b=tracker.begin(), newSearch=catalog.list({search:'2'}); pending[1].resolve({records:[],total:0,page:0,pageSize:50,pageCount:1,counts:{all:1798,czech:808,polish:990}}); await newSearch; assert.ok(tracker.isCurrent(b)); pending[0].resolve({records:[],total:0,page:0,pageSize:50,pageCount:1,counts:{all:1798,czech:808,polish:990}}); await oldSearch; assert.ok(!tracker.isCurrent(a));
  const candidateInput={serviceDate:'2026-07-29',serviceLanguage:'czech',candidateUsages:[]}; const candidateBefore=await invoke('queryCandidates',candidateInput,roles[0]); const preferenceBefore=await invoke('getReferencePreferenceAggregate',{referenceSongId:'czech:1'},admin); const repertoireBefore=await invoke('getReferenceRepertoireMembership',{referenceSongId:'czech:1'},roles[1]); await invoke(MERGE,{referenceSongId:'czech:20',mergeWithReferenceSongId:'czech:21'},admin); assert.deepEqual(await invoke('queryCandidates',candidateInput,roles[0]),candidateBefore); assert.deepEqual(await invoke('getReferencePreferenceAggregate',{referenceSongId:'czech:1'},admin),preferenceBefore); assert.deepEqual(await invoke('getReferenceRepertoireMembership',{referenceSongId:'czech:1'},roles[1]),repertoireBefore);
  // 21, 23-25: deterministic UI gates, memory denial, unchanged legacy/candidate/preference/repertoire boundaries.
  const ui=await readFile(new URL('../app/planning-lifecycle-client.tsx',import.meta.url),'utf8'); for(const pattern of [/aria-label="Same melody"/,/selectedRole === "admin"/,/referenceClient\.list\(\{ language: "all", search: query/,/Select a Reference song/,/already linked/,/runtimeMode !== "db"/,/referenceMelodyRequests\.current\.isCurrent/]) assert.match(ui,pattern); assert.doesNotMatch(ui,/referenceMelodyTarget[^\n]*czech:/); const memory=ui.slice(ui.indexOf('export class MemoryInteractionClient'),ui.indexOf('class DbCatalogClient')); assert.match(memory,/getReferenceMelodyClass\(\).*permissionDenied/); assert.match(memory,/mergeReferenceMelodyClasses\(\).*permissionDenied/);
  direct=new Pool({connectionString:url}); try { assert.equal((await direct.query("select count(*)::int n from melody_equivalence_classes")).rows[0].n,3); assert.equal((await direct.query("select count(*)::int n from song_melody_equivalence")).rows[0].n,4); assert.equal((await direct.query("select count(*)::int n from reference_song_preferences where reference_song_id='czech:1'")).rows[0].n,1); assert.equal((await direct.query("select count(*)::int n from reference_organist_repertoire where reference_song_id='czech:1'")).rows[0].n,1); } finally { await direct.end(); }
 },async()=>{const [terminate,drop]=dropDatabaseSql(name);await control.query(terminate,[name]);await control.query(drop);});
  assert.equal((await control.query('select 1 from pg_database where datname=$1',[name])).rows.length,0); const guardPool=new Pool({connectionString:guardUrl}); try { assert.equal(await fingerprint(guardPool),before); } finally { await guardPool.end(); } console.log("Phase 31.8 authoritative reference melody equivalence: PASS");
 } finally { process.env.DATABASE_URL=guardUrl; if(oldRuntime===undefined) delete process.env.ORGANY_RUNTIME; else process.env.ORGANY_RUNTIME=oldRuntime; await control.end(); }
}
void main().catch(error=>{console.error("Phase 31.8 authoritative reference melody equivalence: FAIL");console.error(error);process.exitCode=1;});
