import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import { Pool } from "pg";
import { POST } from "../app/api/interaction/route";
import { POST as referenceCatalogPost } from "../app/api/reference-catalog/route";
import { DbInteractionClient, MemoryInteractionClient } from "../app/planning-lifecycle-client";
import { InMemoryInteractionRepository } from "../src/application/interaction-contracts";
import { DbReferenceCatalogClient } from "../src/application/reference-catalog-client";
import { seedDemoInteractionKnowledge } from "../src/application/interaction-seed";
import { loadAndValidateReferenceCatalog, synchronizeReferenceCatalog } from "../src/application/reference-catalog-sync";
import { PgReferenceMelodyRepository } from "../src/application/reference-melody";
import { ReferenceMelodyRequestStateController } from "../src/application/reference-melody-request-state";
import { createDatabaseSql, createNpmInvocation, deriveControlUrl, deriveDatabaseUrl, dropDatabaseSql, generateE1DatabaseName, parseGuardDatabaseUrl, withCleanup } from "./engineering-e1-core";

type Result = { status: number; body: any }; type Actor = { userId: string; role?: any };
const GET = "getReferenceMelodyClass", MERGE = "mergeReferenceMelodyClasses";
const run = (name: string, url: string) => new Promise<void>((resolve, reject) => { const command = createNpmInvocation(process.execPath, process.env.npm_execpath, ["run", name]); const child = spawn(command.command, command.args, { env: { ...process.env, DATABASE_URL: url }, stdio: "inherit" }); child.on("error", reject); child.on("close", (code) => code === 0 ? resolve() : reject(new Error(`${name} failed (${code})`))); });
async function invoke(action: string, input: unknown, actor: unknown): Promise<Result> { const response = await POST(new Request("http://localhost/api/interaction", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, input, actor }) })); return { status: response.status, body: await response.json() }; }
async function invokeReferenceCatalog(action: "list" | "getById", input: unknown): Promise<unknown> { const response=await referenceCatalogPost(new Request("http://localhost/api/reference-catalog",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,input})})); assert.equal(response.status,200); return response.json(); }
async function fingerprint(pool: Pool): Promise<string> { const tables=(await pool.query("select tablename from pg_tables where schemaname='public' order by tablename")).rows.map(r=>String(r.tablename)); const content:any[]=[]; for(const table of tables){ if(!/^[a-z_]+$/.test(table)) throw new Error("Unsafe table name"); const row=await pool.query(`select count(*)::int count,coalesce(md5(string_agg(row_to_json(t)::text,',' order by row_to_json(t)::text)),md5('')) digest from ${table} t`); content.push([table,row.rows[0]]); } return JSON.stringify(content); }
async function authoritativeSnapshot(pool: Pool): Promise<string> { const queries=["select * from reference_catalog_songs order by id","select * from reference_song_preferences order by profile_id,reference_song_id","select * from reference_organist_repertoire order by organist_person_id,reference_song_id","select * from reference_melody_classes order by id","select * from reference_song_melody_memberships order by reference_song_id"]; return JSON.stringify(await Promise.all(queries.map(async q=>(await pool.query(q)).rows))); }
async function dbClass(pool: Pool, id: string) { const repo=new PgReferenceMelodyRepository(pool); const value=await repo.getReferenceMelodyClass(id); assert.ok(value); return value; }
function exact(value: any, anchor: string, size?: number) { assert.deepEqual(Object.keys(value).sort(), ["classId", "members", "referenceSongId"]); assert.equal(value.referenceSongId, anchor); if (size !== undefined) assert.equal(value.members.length, size); const ids = new Set<string>(); for (const member of value.members) { assert.deepEqual(Object.keys(member).sort(), ["canonicalNumber", "displayNumber", "language", "referenceSongId", "title"]); assert.ok(!ids.has(member.referenceSongId)); ids.add(member.referenceSongId); } }
async function error(action: string, input: unknown, actor: unknown, code: string) { const result = await invoke(action, input, actor); assert.equal(result.body.error?.code, code, `${action}: ${JSON.stringify(result.body)}`); }
type Deferred = { actual: Promise<Result>; resolve(value: unknown): void };
async function stale(label: string, older: (client: DbInteractionClient) => Promise<any>, newer: (client: DbInteractionClient) => Promise<any>, expected: { referenceSongId?: string; merge?: boolean }, between: () => void = () => undefined) { const pending: Deferred[]=[]; const client=new DbInteractionClient(((action:string,input:unknown,actor?:Actor)=>new Promise((resolve)=>pending.push({actual:invoke(action,input,actor),resolve}))) as any); const state=new ReferenceMelodyRequestStateController(); const oldToken=expected.merge?state.beginMerge():state.beginRead(); const oldPromise=older(client); const oldActual=await pending[0].actual; between(); const newToken=expected.merge?state.beginMerge():state.beginRead(); const newPromise=newer(client); const newActual=await pending[1].actual; pending[1].resolve(newActual.body); const current=await newPromise; if(current.success) state.complete(newToken,expected.merge?{mergeResult:current.value,melody:current.value}:{melody:current.value}); pending[0].resolve(oldActual.body); const obsolete=await oldPromise; if(obsolete.success) state.complete(oldToken,expected.merge?{mergeResult:obsolete.value,melody:obsolete.value}:{melody:obsolete.value}); const snapshot=state.snapshot(); const result=expected.merge?snapshot.mergeResult:snapshot.melody; assert.equal(result?.referenceSongId,expected.referenceSongId,`${label} allowed stale response`); }

async function main() {
 if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required for Phase 31.8 verification.");
 const guardUrl=process.env.DATABASE_URL, guard=parseGuardDatabaseUrl(guardUrl), control=new Pool({connectionString:deriveControlUrl(guard)}), initialGuardPool=new Pool({connectionString:guardUrl}); const before=await fingerprint(initialGuardPool); await initialGuardPool.end(); const name=generateE1DatabaseName(); await control.query(createDatabaseSql(name)); const url=deriveDatabaseUrl(guard,name), oldRuntime=process.env.ORGANY_RUNTIME;
 try { await withCleanup(async()=>{
  await run("db:migrate",url); await run("db:sync:reference-catalog",url); process.env.DATABASE_URL=url; process.env.ORGANY_RUNTIME="db"; const db=new Pool({connectionString:url});
  try {
   // 1-3: full schema, constraints, index, counts, and one membership per song.
   const columns=await db.query("select table_name,column_name,is_nullable,column_default,data_type from information_schema.columns where table_name in ('reference_melody_classes','reference_song_melody_memberships') order by table_name,ordinal_position"); assert.equal(columns.rows.length,6); assert.ok(columns.rows.every(r=>r.is_nullable==='NO')); assert.ok(columns.rows.filter(r=>String(r.column_name).endsWith('_at')).every(r=>String(r.data_type).includes('timestamp')&&r.column_default));
   const constraints=await db.query("select table_name,constraint_type from information_schema.table_constraints where table_name in ('reference_melody_classes','reference_song_melody_memberships')"); assert.equal(constraints.rows.filter(r=>r.constraint_type==='PRIMARY KEY').length,2); assert.equal(constraints.rows.filter(r=>r.constraint_type==='FOREIGN KEY').length,2);
   const cascades=await db.query("select rc.delete_rule from information_schema.referential_constraints rc join information_schema.table_constraints tc on tc.constraint_name=rc.constraint_name where tc.table_name='reference_song_melody_memberships' order by tc.constraint_name"); assert.deepEqual(cascades.rows,[{delete_rule:'CASCADE'},{delete_rule:'CASCADE'}]);
   assert.match(String((await db.query("select indexdef from pg_indexes where indexname='reference_song_melody_memberships_class_id_idx'")).rows[0].indexdef),/class_id/);
   assert.deepEqual((await db.query("select (select count(*)::int from reference_catalog_songs) songs,(select count(*)::int from reference_song_melody_memberships) memberships,(select count(*)::int from reference_melody_classes) classes,(select count(*)::int from (select c.id from reference_melody_classes c join reference_song_melody_memberships m on m.class_id=c.id group by c.id having count(*)<>1)x) non_singletons")).rows[0],{songs:1798,memberships:1798,classes:1798,non_singletons:0});
   await seedDemoInteractionKnowledge(db); await db.query("insert into app_user_roles(user_id,role) values ('demo-organist-user','admin') on conflict do nothing; insert into app_users(id,display_name,active) values ('inactive-melody-user','Inactive',false),('roleless-melody-user','Roleless',true)");
  } finally { await db.end(); }
  const roles:Actor[]=[{userId:'demo-priest-user',role:'priest'},{userId:'demo-organist-user',role:'organist'},{userId:'demo-admin-user',role:'admin'},{userId:'demo-member-user',role:'congregationMember'}], admin=roles[2];
  // 4-14: exact DTO, ordering, every role, permission and complete structured validation.
  for(const actor of roles){const r=await invoke(GET,{referenceSongId:'czech:1'},actor);assert.equal(r.status,200);exact(r.body.value,'czech:1',1);}
  for(const actor of [roles[0],roles[1],roles[3]]) await error(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:2'},actor,'permissionDenied');
  for(const input of [null,{}, {referenceSongId:1},{referenceSongId:'czech:1',extra:true}]) await error(GET,input,admin,'invalidInput');
  for(const input of [null,{}, {referenceSongId:'czech:1'}, {referenceSongId:'czech:1',mergeWithReferenceSongId:2},{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:2',extra:true}]) await error(MERGE,input,admin,'invalidInput');
  for(const actor of [null,{}, {userId:''},{userId:'demo-admin-user',role:'bad'},{userId:'demo-admin-user',role:'admin',extra:true}]) { await error(GET,{referenceSongId:'czech:1'},actor,'invalidInput'); await error(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:2'},actor,'invalidInput'); }
  for(const actor of [{userId:'missing',role:'admin'},{userId:'demo-priest-user',role:'admin'},{userId:'inactive-melody-user',role:'admin'},{userId:'roleless-melody-user'}]) { await error(GET,{referenceSongId:'czech:1'},actor,'permissionDenied'); await error(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:2'},actor,'permissionDenied'); }
  await error(GET,{referenceSongId:'czech:999999'},admin,'notFound'); await error(MERGE,{referenceSongId:'czech:999999',mergeWithReferenceSongId:'czech:1'},admin,'notFound'); await error(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:999999'},admin,'notFound');
  const self=await invoke(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:1'},admin); exact(self.body.value,'czech:1',1);
  let direct: Pool; const pair=await invoke(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:2'},admin); exact(pair.body.value,'czech:1',2); assert.equal(pair.body.value.classId,'reference-melody:czech:1'); direct=new Pool({connectionString:url}); assert.equal((await direct.query("select count(*)::int n from reference_melody_classes where id='reference-melody:czech:2'")).rows[0].n,0); await direct.end(); assert.deepEqual((await invoke(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:2'},admin)).body.value,pair.body.value);
  await invoke(MERGE,{referenceSongId:'czech:3',mergeWithReferenceSongId:'czech:4'},admin); const multi=await invoke(MERGE,{referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:3'},admin); exact(multi.body.value,'czech:1',4); assert.deepEqual(multi.body.value.members.map((m:any)=>m.canonicalNumber),[1,2,3,4]);
  const crossLanguage=await invoke(MERGE,{referenceSongId:'czech:5',mergeWithReferenceSongId:'polish:1'},admin); exact(crossLanguage.body.value,'czech:5',2); assert.deepEqual(crossLanguage.body.value.members.map((m:any)=>[m.language,m.canonicalNumber]),[['czech',5],['polish',1]]); assert.equal(crossLanguage.body.value.classId,'reference-melody:czech:5');
  // 15-16: injected rollback and genuinely overlapping concurrent merges.
  direct=new Pool({connectionString:url}); try { const affected=async()=>JSON.stringify({classes:(await direct.query("select * from reference_melody_classes where id in ('reference-melody:czech:22','reference-melody:czech:23') order by id")).rows,memberships:(await direct.query("select * from reference_song_melody_memberships where reference_song_id in ('czech:22','czech:23') order by reference_song_id")).rows}); const rollbackBefore=await affected(); const failing=new PgReferenceMelodyRepository(direct,{failAfterMembershipMove:true}); await assert.rejects(()=>failing.mergeReferenceMelodyClasses('czech:22','czech:23')); assert.equal(await affected(),rollbackBefore); } finally { await direct.end(); }
  await Promise.all([invoke(MERGE,{referenceSongId:'czech:7',mergeWithReferenceSongId:'czech:8'},admin),invoke(MERGE,{referenceSongId:'czech:9',mergeWithReferenceSongId:'czech:8'},admin)]); direct=new Pool({connectionString:url}); try { const state=await direct.query("select (select count(*)::int from reference_song_melody_memberships) memberships,(select count(*)::int from reference_song_melody_memberships m left join reference_melody_classes c on c.id=m.class_id where c.id is null) dangling,(select count(*)::int from reference_melody_classes c left join reference_song_melody_memberships m on m.class_id=c.id where m.class_id is null) orphans,(select count(*)::int from (select reference_song_id from reference_song_melody_memberships group by reference_song_id having count(*)>1)x) duplicates"); assert.deepEqual(state.rows[0],{memberships:1798,dangling:0,orphans:0,duplicates:0}); const overlap=await dbClass(direct,'czech:8'); assert.deepEqual(overlap.members.map((m:any)=>m.referenceSongId),['czech:7','czech:8','czech:9']); assert.ok(['reference-melody:czech:7','reference-melody:czech:9'].includes(overlap.classId)); assert.equal((await direct.query("select count(*)::int n from reference_melody_classes where id=$1",[overlap.classId])).rows[0].n,1); } finally { await direct.end(); }
  // 17-19: reconcile seam proves preservation, explicit dependent/orphan cleanup, singleton creation and complete rollback.
  const frozen=await loadAndValidateReferenceCatalog(), removed=frozen.at(-1)!, synthetic={...removed,id:`${removed.language}:999999`,canonicalNumber:999999,sourceId:'phase-31-8-test',title:'Acceptance-only song',sourceUrl:null}, derived=[...frozen.slice(0,-1),synthetic]; direct=new Pool({connectionString:url}); try {
    await direct.query("insert into reference_song_preferences(profile_id,reference_song_id,score) values ('pref-priest','czech:1',2),('pref-priest',$1,1) on conflict do nothing",[removed.id]); await direct.query("insert into reference_organist_repertoire(organist_person_id,reference_song_id) values ('demo-organist','czech:1'),('demo-organist',$1) on conflict do nothing",[removed.id]);
    await synchronizeReferenceCatalog(direct,{records:derived,expectedCounts:{czech:808,polish:990,total:1798}});
    const cleanup=await direct.query("select (select count(*)::int from reference_song_preferences where reference_song_id=$1) removed_preferences,(select count(*)::int from reference_organist_repertoire where reference_song_id=$1) removed_repertoire,(select count(*)::int from reference_song_melody_memberships where reference_song_id=$1) removed_membership,(select count(*)::int from reference_melody_classes where id=$2) empty_class,(select count(*)::int from reference_song_melody_memberships where reference_song_id=$3 and class_id=$4) added_membership,(select count(*)::int from reference_melody_classes where id=$4) added_class",[removed.id,`reference-melody:${removed.id}`,synthetic.id,`reference-melody:${synthetic.id}`]); assert.deepEqual(cleanup.rows[0],{removed_preferences:0,removed_repertoire:0,removed_membership:0,empty_class:0,added_membership:1,added_class:1});
    assert.deepEqual((await dbClass(direct,synthetic.id)).members.map(m=>m.referenceSongId),[synthetic.id]); assert.equal((await direct.query("select count(*)::int n from reference_song_preferences where reference_song_id='czech:1'")).rows[0].n,1); assert.equal((await direct.query("select count(*)::int n from reference_organist_repertoire where reference_song_id='czech:1'")).rows[0].n,1);
    const beforeFailure=await authoritativeSnapshot(direct); await assert.rejects(()=>synchronizeReferenceCatalog(direct,{records:frozen,failBeforeCommit:true})); assert.equal(await authoritativeSnapshot(direct),beforeFailure);
    await synchronizeReferenceCatalog(direct); assert.equal((await direct.query("select count(*)::int n from reference_catalog_songs where id=$1",[synthetic.id])).rows[0].n,0); assert.deepEqual((await dbClass(direct,removed.id)).members.map(m=>m.referenceSongId),[removed.id]);
  } finally { await direct.end(); }
  // 20 and 22: actual browser DB client and genuinely deferred transport in reverse order.
  const browser=new DbInteractionClient(async(action: string,input: unknown,actor?: Actor)=>(await invoke(action,input,actor)).body); exact((await browser.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:1'})).value,'czech:1',4); exact((await browser.mergeReferenceMelodyClasses({actor:admin as any,referenceSongId:'czech:10',mergeWithReferenceSongId:'czech:11'})).value,'czech:10',2);
  const scoped=new ReferenceMelodyRequestStateController(), obsoleteRead=scoped.beginRead(), obsoleteSearch=scoped.beginSearch(), obsoleteMerge=scoped.beginMerge(); scoped.contextChanged(); assert.equal(scoped.isCurrent(obsoleteRead),false); assert.equal(scoped.isCurrent(obsoleteSearch),false); assert.equal(scoped.isCurrent(obsoleteMerge),false); const concurrentRead=scoped.beginRead(); scoped.beginSearch(); assert.equal(scoped.isCurrent(concurrentRead),true,'search must not invalidate the current class read'); const olderRead=scoped.beginRead(), newerRead=scoped.beginRead(); assert.equal(scoped.isCurrent(olderRead),false); assert.equal(scoped.isCurrent(newerRead),true); const olderSearch=scoped.beginSearch(), newerSearch=scoped.beginSearch(); assert.equal(scoped.isCurrent(olderSearch),false); assert.equal(scoped.isCurrent(newerSearch),true); const pendingMerge=scoped.beginMerge(); scoped.selectTarget('czech:2'); assert.equal(scoped.isCurrent(pendingMerge),false); const newerMerge=scoped.beginMerge(); assert.equal(scoped.isCurrent(newerMerge),true);
  const componentState=new ReferenceMelodyRequestStateController(); componentState.contextChanged(); assert.deepEqual(componentState.snapshot(),{melody:null,searchResults:[],selectedTarget:'',mergeResult:null}); const initialToken=componentState.beginRead(), initialResult=await browser.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:1'}); assert.ok(initialResult.success); componentState.complete(initialToken,{melody:initialResult.value}); assert.equal(componentState.snapshot().melody?.referenceSongId,'czech:1'); assert.deepEqual(componentState.snapshot().searchResults,[]); assert.equal(componentState.snapshot().selectedTarget,''); const actualCatalog=new DbReferenceCatalogClient(invokeReferenceCatalog); const searchToken=componentState.beginSearch(), actualSearch=await actualCatalog.list({language:'all',search:'2',page:0,pageSize:10}); componentState.complete(searchToken,{searchResults:actualSearch.records}); assert.ok(componentState.snapshot().searchResults.length>0); assert.equal(componentState.snapshot().melody?.referenceSongId,'czech:1'); componentState.selectTarget('czech:2'); assert.equal(componentState.snapshot().selectedTarget,'czech:2'); const mergeToken=componentState.beginMerge(), componentMerge=await browser.mergeReferenceMelodyClasses({actor:admin as any,referenceSongId:'czech:1',mergeWithReferenceSongId:'czech:2'}); assert.ok(componentMerge.success); componentState.complete(mergeToken,{melody:componentMerge.value,mergeResult:componentMerge.value}); assert.equal(componentState.snapshot().mergeResult?.referenceSongId,'czech:1'); assert.equal(componentState.snapshot().selectedTarget,'czech:2');
  await stale('song',c=>c.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:1'}),c=>c.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:10'}),{referenceSongId:'czech:10'}); await stale('actor',c=>c.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:1'}),c=>c.getReferenceMelodyClass({actor:roles[0] as any,referenceSongId:'czech:1'}),{referenceSongId:'czech:1'}); await stale('role',c=>c.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:1'}),c=>c.getReferenceMelodyClass({actor:{userId:'demo-admin-user'} as any,referenceSongId:'czech:1'}),{referenceSongId:'czech:1'}); process.env.ORGANY_RUNTIME='db'; await stale('runtime',c=>c.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:1'}),c=>c.getReferenceMelodyClass({actor:admin as any,referenceSongId:'czech:1'}),{referenceSongId:undefined},()=>{process.env.ORGANY_RUNTIME='memory';}); process.env.ORGANY_RUNTIME='db'; await stale('merge target',c=>c.mergeReferenceMelodyClasses({actor:admin as any,referenceSongId:'czech:15',mergeWithReferenceSongId:'czech:16'}),c=>c.mergeReferenceMelodyClasses({actor:admin as any,referenceSongId:'czech:15',mergeWithReferenceSongId:'czech:17'}),{referenceSongId:'czech:15',merge:true}); await stale('competing merge',c=>c.mergeReferenceMelodyClasses({actor:admin as any,referenceSongId:'czech:12',mergeWithReferenceSongId:'czech:13'}),c=>c.mergeReferenceMelodyClasses({actor:admin as any,referenceSongId:'czech:12',mergeWithReferenceSongId:'czech:14'}),{referenceSongId:'czech:12',merge:true});
  const pending:any[]=[]; const catalog=new DbReferenceCatalogClient(((action: "list" | "getById",input: unknown)=>new Promise(resolve=>pending.push({action,input,resolve}))) as any); const searchState=new ReferenceMelodyRequestStateController(); const a=searchState.beginSearch(), oldSearch=catalog.list({search:'1'}), b=searchState.beginSearch(), newSearch=catalog.list({search:'2'}); const currentRecord={id:'czech:2',language:'czech',canonicalNumber:2,displayNumber:'2',title:'Current search'} as const; const staleRecord={id:'czech:1',language:'czech',canonicalNumber:1,displayNumber:'1',title:'Stale search'} as const; pending[1].resolve({records:[currentRecord],total:1,page:0,pageSize:50,pageCount:1,counts:{all:1798,czech:808,polish:990}}); const currentSearch=await newSearch; searchState.complete(b,{searchResults:currentSearch.records,selectedTarget:currentSearch.records[0]?.id??''}); assert.deepEqual(searchState.snapshot().searchResults,[currentRecord]); assert.equal(searchState.snapshot().selectedTarget,'czech:2'); pending[0].resolve({records:[staleRecord],total:1,page:0,pageSize:50,pageCount:1,counts:{all:1798,czech:808,polish:990}}); const oldSearchResult=await oldSearch; searchState.complete(a,{searchResults:oldSearchResult.records,selectedTarget:'stale'}); assert.deepEqual(searchState.snapshot().searchResults,[currentRecord]); assert.equal(searchState.snapshot().selectedTarget,'czech:2');
  direct=new Pool({connectionString:url}); const legacyBefore=JSON.stringify({classes:(await direct.query('select * from melody_equivalence_classes order by id')).rows,memberships:(await direct.query('select * from song_melody_equivalence order by song_id,class_id')).rows}); await direct.end(); const candidateInput={serviceDate:'2026-07-29',serviceLanguage:'czech',candidateUsages:[]}; const candidateBefore=await invoke('queryCandidates',candidateInput,roles[0]); const preferenceBefore=await invoke('getReferencePreferenceAggregate',{referenceSongId:'czech:1'},admin); const repertoireBefore=await invoke('getReferenceRepertoireMembership',{referenceSongId:'czech:1'},roles[1]); await invoke(MERGE,{referenceSongId:'czech:20',mergeWithReferenceSongId:'czech:21'},admin); assert.deepEqual(await invoke('queryCandidates',candidateInput,roles[0]),candidateBefore); assert.deepEqual(await invoke('getReferencePreferenceAggregate',{referenceSongId:'czech:1'},admin),preferenceBefore); assert.deepEqual(await invoke('getReferenceRepertoireMembership',{referenceSongId:'czech:1'},roles[1]),repertoireBefore); direct=new Pool({connectionString:url}); const legacyAfter=JSON.stringify({classes:(await direct.query('select * from melody_equivalence_classes order by id')).rows,memberships:(await direct.query('select * from song_melody_equivalence order by song_id,class_id')).rows}); await direct.end(); assert.equal(legacyAfter,legacyBefore);
  // 21, 23-25: deterministic UI gates, memory denial, unchanged legacy/candidate/preference/repertoire boundaries.
  const ui=await readFile(new URL('../app/planning-lifecycle-client.tsx',import.meta.url),'utf8'); for(const pattern of [/aria-label="Same melody"/,/selectedRole === "admin"/,/referenceClient\.list\(\{ language: "all", search: query/,/Select a Reference song/,/already linked/,/runtimeMode !== "db"/,/referenceMelodyState\.current\.complete/]) assert.match(ui,pattern); assert.doesNotMatch(ui,/referenceMelodyTarget[^\n]*czech:/); const memory=ui.slice(ui.indexOf('export class MemoryInteractionClient'),ui.indexOf('class DbCatalogClient')); assert.match(memory,/getReferenceMelodyClass\(\).*permissionDenied/); assert.match(memory,/mergeReferenceMelodyClasses\(\).*permissionDenied/);
  const memoryClient=new MemoryInteractionClient(new InMemoryInteractionRepository(),{} as any); assert.equal((await memoryClient.getReferenceMelodyClass()).error.code,'permissionDenied'); assert.equal((await memoryClient.mergeReferenceMelodyClasses()).error.code,'permissionDenied'); direct=new Pool({connectionString:url}); try { assert.equal((await direct.query("select count(*)::int n from reference_song_preferences where reference_song_id='czech:1'")).rows[0].n,1); assert.equal((await direct.query("select count(*)::int n from reference_organist_repertoire where reference_song_id='czech:1'")).rows[0].n,1); } finally { await direct.end(); }
 },async()=>{const [terminate,drop]=dropDatabaseSql(name);await control.query(terminate,[name]);await control.query(drop);});
  assert.equal((await control.query('select 1 from pg_database where datname=$1',[name])).rows.length,0); const guardPool=new Pool({connectionString:guardUrl}); try { assert.equal(await fingerprint(guardPool),before); } finally { await guardPool.end(); } console.log("Phase 31.8 authoritative reference melody equivalence: PASS");
 } finally { process.env.DATABASE_URL=guardUrl; if(oldRuntime===undefined) delete process.env.ORGANY_RUNTIME; else process.env.ORGANY_RUNTIME=oldRuntime; await control.end(); }
}
void main().catch(error=>{console.error("Phase 31.8 authoritative reference melody equivalence: FAIL");console.error(error);process.exitCode=1;});
