import type { Pool } from "pg";
import type { InteractionRepository } from "./interaction-service";
import type { AppUser, KnowledgeMapping, MelodyClass, MelodyNonRepetitionConfig, PreferenceProfile, SongPreference } from "./interaction-contracts";
import type { PlanningRole } from "../planning-lifecycle";

export class PgInteractionRepository implements InteractionRepository {
  constructor(private readonly pool: Pool) {}
  async listUsers(): Promise<AppUser[]> { const { rows } = await this.pool.query("select u.id, u.display_name, u.person_id, u.active, coalesce(array_agg(r.role) filter (where r.role is not null), '{}') as roles from app_users u left join app_user_roles r on r.user_id = u.id group by u.id order by u.id"); return rows.map((r) => ({ id: String(r.id), displayName: String(r.display_name), ...(r.person_id ? { personId: String(r.person_id) } : {}), active: Boolean(r.active), roles: normalizeRoles(r.roles) })); }
  async listProfiles(): Promise<PreferenceProfile[]> { const { rows } = await this.pool.query("select id, user_id, category from preference_profiles order by id"); return rows.map((r) => ({ id: String(r.id), userId: String(r.user_id), category: fromDbCategory(String(r.category)) })); }
  async listPreferences(): Promise<SongPreference[]> { const { rows } = await this.pool.query("select profile_id, song_id, score from song_preferences"); return rows.map((r) => ({ profileId: String(r.profile_id), songId: String(r.song_id), score: Number(r.score) })); }
  async upsertPreference(preference: SongPreference): Promise<SongPreference> { await this.pool.query("insert into song_preferences (profile_id, song_id, score) values ($1, $2, $3) on conflict (profile_id, song_id) do update set score = excluded.score, updated_at = now()", [preference.profileId, preference.songId, preference.score]); return preference; }
  async listRepertoire(organistPersonId: string): Promise<string[]> { const { rows } = await this.pool.query("select song_id from organist_repertoire where organist_person_id = $1 order by song_id", [organistPersonId]); return rows.map((r) => String(r.song_id)); }
  async setRepertoire(organistPersonId: string, songId: string, active: boolean): Promise<void> { if (active) await this.pool.query("insert into organist_repertoire (organist_person_id, song_id) values ($1, $2) on conflict do nothing", [organistPersonId, songId]); else await this.pool.query("delete from organist_repertoire where organist_person_id = $1 and song_id = $2", [organistPersonId, songId]); }
  async listMelodyClasses(): Promise<MelodyClass[]> { const { rows } = await this.pool.query("select c.id, c.label, c.synthetic, coalesce(array_agg(s.song_id) filter (where s.song_id is not null), '{}') as song_ids from melody_equivalence_classes c left join song_melody_equivalence s on s.class_id = c.id group by c.id order by c.id"); return rows.map((r) => ({ id: String(r.id), label: String(r.label), synthetic: Boolean(r.synthetic), songIds: normalizeTextArray(r.song_ids) })); }
  async listKnowledge(): Promise<{ antiphons: KnowledgeMapping[]; seasons: KnowledgeMapping[]; melodyWindow: MelodyNonRepetitionConfig; melodyClasses: MelodyClass[] }> { const [antiphons, seasons, melodyWindow, melodyClasses] = await Promise.all([this.listMappings("antiphon_mappings", "antiphon_key"), this.listMappings("liturgical_season_mappings", "season_key"), this.getMelodyWindow(), this.listMelodyClasses()]); return { antiphons, seasons, melodyWindow, melodyClasses }; }
  async setMelodyWindow(config: MelodyNonRepetitionConfig): Promise<MelodyNonRepetitionConfig> { await this.pool.query("insert into melody_non_repetition_config (id, days_before, days_after) values ('global', $1, $2) on conflict (id) do update set days_before = excluded.days_before, days_after = excluded.days_after, updated_at = now()", [config.daysBefore, config.daysAfter]); return config; }
  private async getMelodyWindow() { const { rows } = await this.pool.query("select days_before, days_after from melody_non_repetition_config where id = 'global'"); return rows[0] ? { daysBefore: Number(rows[0].days_before), daysAfter: Number(rows[0].days_after) } : { daysBefore: 14, daysAfter: 0 }; }
  private async listMappings(table: "antiphon_mappings" | "liturgical_season_mappings", keyColumn: "antiphon_key" | "season_key"): Promise<KnowledgeMapping[]> { const { rows } = await this.pool.query(`select id, ${keyColumn} as key, song_id, synthetic from ${table} order by id`); return rows.map((r) => ({ id: String(r.id), key: String(r.key), songId: String(r.song_id), synthetic: Boolean(r.synthetic) })); }
}
function fromDbCategory(category: string): "priest" | "organist" | "congregationMember" { return category === "congregation_member" ? "congregationMember" : category as "priest" | "organist"; }
function normalizeRoles(value: unknown): PlanningRole[] { return normalizeTextArray(value).map((role) => role === "congregation_member" ? "congregationMember" : role as PlanningRole); }
function normalizeTextArray(value: unknown): string[] { return Array.isArray(value) ? value.map(String) : typeof value === "string" ? value.replace(/[{}]/g, "").split(",").filter(Boolean) : []; }
